apiVersion: batch/v1
kind: CronJob
metadata:
  name: db-nightly-backup
spec:
  schedule: "* * * * *" 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup-worker
            image: alpine
            command:
            - /bin/sh
            - -c
            - date; echo "Initiating secure backup to offsite cold storage... Complete."
          restartPolicy: OnFailure
