apiVersion: batch/v1
kind: Job
metadata:
  name: indexed-data-processor
spec:
  completions: 3
  parallelism: 3
  completionMode: Indexed 
  template:
    spec:
      containers:
      - name: processor
        image: alpine
        command: 
        - /bin/sh
        - -c
        - |
          echo "I am worker node: $JOB_COMPLETION_INDEX"
          echo "Processing database partition $JOB_COMPLETION_INDEX..."
          sleep 3
      restartPolicy: Never
