apiVersion: batch/v1
kind: CronJob
metadata:
  name: paused-report-generator
spec:
  schedule: "* * * * *"
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: report
            image: alpine
            command: ["echo", "I will never run until suspend is set to false."]
          restartPolicy: OnFailure
