apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  namespace: enterprise-prod
  annotations:
    argocd.argoproj.io/sync-wave: "1" 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: nginx:alpine