apiVersion: v1
kind: Pod
metadata:
  name: greedy-pod
  namespace: strict-prod
spec:
  containers:
  - name: app
    image: nginxinc/nginx-unprivileged:1.24.0
    resources:
      requests:
        memory: "2Gi"
      limits:
        memory: "2Gi" 