apiVersion: v1
kind: Service
metadata:
  name: gitops-nginx-svc
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: gitops-nginx 
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: mesh-gateway
spec:
  selector:
    istio: ingress 
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: nginx-mesh-route
spec:
  hosts:
  - "*"
  gateways:
  - mesh-gateway
  http:
  - fault:
      delay:
        percentage:
          value: 50.0
        fixedDelay: 3s
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: gitops-nginx-svc
        port:
          number: 80
    