apiVersion: apps/v1
kind: Deployment
metadata:
  name: automated-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: my-docker-username/my-api:v1.0.0