images:
- name: DARKANGEL689/my-api
  newName: darkangel689/my-api
  newTag: 4da26f7b3ca21ffd851142b9bbdf16f9fc56d035
- name: darkangel689/my-api
  newName: darkangel689/my-api
  newTag: v2.0.0-latest# Waking up the CI/CD Robot for real!
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
