apiVersion: v1
kind: Service
metadata:
  name: jaeger-svc
  namespace: default
spec:
  ports:
  - name: ui
    port: 16686
    targetPort: 16686
  - name: collector-http
    port: 14268
    targetPort: 14268
  - name: otel-grpc
    port: 4317
    targetPort: 4317
  selector:
    app: jaeger