apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongodb-nightly-backup
spec:
  schedule: "0 2 * * *" 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup-agent
            image: mongo:6.0
            command:
            - /bin/sh
            - -c
            - "mongodump --host mongodb-internal --username admin --password supersecretpassword123 --authenticationDatabase admin --archive=/backup/mongo-archive.gz --gzip && echo 'Backup Successful'"
          restartPolicy: OnFailure