---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: enterprise-db-credentials
  namespace: default
spec:
  encryptedData:
    PASSWORD: AgBL7Cr2SjWPcIkcUyqoR+4Sz3ImEUq8IRDWPt+HwHlpV5MaOZ/4EDKzwRahO+0WXS5yEE+S2JLyg7195/OXNG8N+fGeaDjvF2F+yKiv/pVkBaB5DfPcI21LQmKchpQC8Lrdtscs/sC5g26z7KdBfr8jcTLnR3/EBxue4XqhQsfXw4v12sMQFLM0rScM8s1HRbTcTyzGN6EJ6wXPXMOBn1b0/RFva2zo/6OXvW5IRvQlbz2gPqn68fYVNQbE45ariF1WmDWR5rW677KwQzJxsBE6IipvXnBh5C+F3X74qlfASdeA5uPT5Mq9egw4lIkJDyK68Jat4s7pSk1JU7o3CPT1cZbtOXSORdcLmn6QJQMh8Ipwycdp3fmG6WS6d62d0FBhLScpRsLjGMybojvOVRl3CdKH1bMuygYYXXGUm1SjEZMhYEdL8QEwR0M7bMuOJ8QY2JiQnLy/iop7qQrJ+JZzTWEKCbi5VGb+1BrpDLWmnalBlgnHnSXamrd554g59RTGB2T8cgpu7etTiK3y53vT8lduckQwYLBPOEbMz6VYlFZQhey6dgI1ya7UDKsna+He6O58ZJQ9yNG6qtl9tH1DVM36DXcfIedWSu7FwQMaU5072e3EGSQADQAIf4AbFik4y0pXhKrPG0X/Fv6cLQYjtEJrvNrO3BqrC8uHzoV+ZyeSkPNgVVIVjXIHFyxrXYKjtnTB/Uqu3a5Lv1M88zh03g5Ih7Fer7kvkmZBtUVr0Ig=
    USERNAME: AgBVtemFvSmrtbZPv9cqYwh2tS1HvxlVePpkDDBetqUh1psHAlMKMvIHvUUL8IlqbJatLafBbHFIZE/Mc1LNdpytuTl/Mo687+QvKrU+SyZq41gdltKMpTbIYhzNyRiXLRSreSPg7xFL5ghevGmzeMnckmSxVvCzTOgiawuR/p30GZR5LwSrKpZoaQCx6pmlg2fAHiZhPWcIxbeBuqffwq9ATdS76uJp7OpLvnoibUNeSKePCyLYdUFYUOgH8JU3bSDdbZBfvHTVjaJwmA6UzHqrb+OQg2QeBFDPmlwO3iqs9uAipQmlbjP4a0xJbqmLU84eWtzhHPC49H3a63YQeT5ymGXewDyIkItjhFdebqnVcFIOf+smeipuWn7SM9ckfG5T0IgKnl4FebVzsI4ugpOK4fYBcu50hsIonBe3CnZ51/p2Xx88z+1a0RvmZ7+E3PfMLo3NuJCjml44kXKaqBs5CDgk7mBtGyizT7PPCrvEzoZ368CNFnxS/DzPl0fDSm7E5RBxJxhNzU6o46aa+UuzzdPtx2uoGvq/72LrY+dQcRy5TIMyJt50ZQv3SspMzgbzR+forH6Wf+6/bT8G/9yFdDxAt7UptvX3/AFMuX92MW/Gvo9JHvJI475mgUfr3i8mOLab00MVZZwbpeaGqCHQw1Pw+RiN3EXiyXvdKm0wRahVK5E/luNPLz/KvzhYG5ZugL3UAc+yJt1vSgB7Q9g=
  template:
    metadata:
      creationTimestamp: null
      name: enterprise-db-credentials
      namespace: default
    type: Opaque
