apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-database-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secure-api
  template:
    metadata:
      labels:
        app: secure-api
    spec:
      containers:
      - name: api
        image: alpine
        command: ["/bin/sh", "-c", "echo 'API Online. Credentials mounted securely as files.'; sleep 3600"]
        volumeMounts:
        - name: secret-vault
          mountPath: "/etc/secrets"
          readOnly: true
      volumes:
      - name: secret-vault
        secret:
          secretName: enterprise-db-credentials 