apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-db
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-db
  template:
    metadata:
      labels:
        app: mlflow-db
    spec:
      containers:
      - name: postgres
        image: postgres:14-alpine
        env:
        - name: POSTGRES_USER
          value: "mlops_admin"
        - name: POSTGRES_PASSWORD
          value: "protocol300"
        - name: POSTGRES_DB
          value: "mlflow_lineage"
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-db
  namespace: default
spec:
  selector:
    app: mlflow-db
  ports:
    - port: 5432
      targetPort: 5432