apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  {{- range .Values.appEnvVars }}
  {{ .key }}: {{ .value | quote }}
  {{- end }}
  CLUSTER_ADMIN: {{ .Values.adminName | default "system-bot" | quote }}
  RELEASE_NAME: {{ .Release.Name }}
  NAMESPACE: {{ .Release.Namespace }}