apiVersion: apps/v1
kind: Deployment
metadata:
  name: enterprise-wasm-api
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wasm-api
  template:
    metadata:
      labels:
        app: wasm-api
    spec:
      runtimeClassName: wasmtime-spin
      containers:
      - name: wasm-microservice
        image: ghcr.io/fermyon/spin-helloworld:v1.0.0
        command: ["/"]
        resources:
          limits:
            cpu: "100m"
            memory: "32Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: wasm-api-svc
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: wasm-api