apiVersion: v1
kind: Pod
metadata:
  name: backend-db
  labels:
    app: database
spec:
  containers:
  - name: db
    image: nginx:alpine
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  selector:
    app: database
  ports:
  - port: 80