apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: simulated-enterprise-vault
  namespace: default
spec:
  provider:
    fake:
      data:
        - key: production-database-credentials
          valueMap:
            username: "admin-architect"
            password: "SuperSecretQuantumPassword3000!"