apiVersion: apps/v1
kind: Deployment
metadata:
  name: optimized-billing-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cheap-api
  template:
    metadata:
      labels:
        app: cheap-api
    spec:
      containers:
      - name: web
        image: nginx:alpine
        resources:
          requests:
            cpu: "100m"  
            memory: "128Mi"