apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: api-assassination-test
  namespace: default
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      "app": "resilient-api"
  scheduler:
    cron: "@every 10s"