apiVersion: v1
kind: Pod
metadata:
  name: cache-loader-app
  labels:
    app: traffic-test
spec:
  containers:
  - name: web
    image: nginx:alpine
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 2
      periodSeconds: 3