apiVersion: policy.karmada.io/v1alpha1
kind: OverridePolicy
metadata:
  name: geographic-mutation-policy
  namespace: default
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: global-enterprise-api
  targetCluster:
    clusterNames:
      - member1
  overriders:
    plaintext:
      - path: "/metadata/labels/region"
        operator: add
        value: "us-east-1"