---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-credentials
  namespace: default
spec:
  encryptedData:
    password: AgBeLm1+e/udOQ3K8+veup2Zq4kak52vvctGz2IFQHIUi1fKrSa7qKgWSgi8CiQOQSeITXh+dqpfuwktPufnDR+LjxAVo21wiepoOCEEILWYPsLAHGPpaXQRJcOIaFsNDeBFR55a0GZAaLhmllzTED1e8GeEjhx1QNjFPMiDCeEupkZX4JGCmi6VVXDA28pROSkUfXyJ/wvRliQzxF9Mxpnfu8EQTnqZ4rVuiJ0BZwghSm5TYBtS/+4MWiFhVFD/mC9osBQQTWdjy72jRTxnYjlls5DVP8j9RCZSixAzySKxAee5RJzoH0EGeAJ1Jo8+C2IX2CJP3m5eIA4t5yHDc1dF2XB4j3bVbkYIHV2rDAIcoOzAH11iZIVziZnV2iYqYSRlquzAT7rnH6O1d55oFWY1nbs8hHhUk510bwkCNUW6pkyFFDEFK8AOkjt6KOmOKQP5aqFLK95RkP4bYs9KOPeSCPRPLvmFpfxglJcCF17vfFtERiv0yaWiHtOvL6kyNa/xDDGK4HXfhW8oXDsoleXZukCR0jBammCz2cchRSlTc9xSBqHVGDN4nbtt7nUgqEIoyKgA+mF4YT/3gVVpbtoviB1alsWrNsTEXbA2WwHem2zu4f79e7+Y58it+p74Vz4QUOKhCSlMNoJll3KLnwlG/JB4J+fjwrBmjTAnZmrZmHrcAaMutdzWMjg9csXZqJ93XcCmKhAzmYQAIFMekBtHPpRaWJszs4aN
  template:
    metadata:
      creationTimestamp: null
      name: db-credentials
      namespace: default
