apiVersion: v1
kind: Pod
metadata:
  name: secret-consumer-pod
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 101
  containers:
  - name: app
    image: nginxinc/nginx-unprivileged:1.24.0
    env:
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: password