apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-facing-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-api
  template:
    metadata:
      labels:
        app: web-api
    spec:
      containers:
      - name: api
        image: nginx:alpine