apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sticky-router
  annotations:
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route-cookie"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /sticky
        pathType: Prefix
        backend:
          service:
            name: video-service
            port:
              number: 80