apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: regex-router
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /assets/.*\.mp4$
        pathType: ImplementationSpecific
        backend:
          service:
            name: video-service
            port:
              number: 80