apiVersion: v1
kind: Pod
metadata:
  name: bulk-server
spec:
  containers:
  - name: app
    image: alpine
    command: ["sleep", "3600"]
    envFrom:
    - configMapRef:
        name: game-server-settings 
