apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  MYSQL_PASSWORD: "SuperSecretPassword123!"
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
    - name: test-container
      image: alpine
      command: ["sleep", "3600"]
      envFrom:
        - secretRef:
            name: db-credentials