apiVersion: v1
kind: Pod
metadata:
  name: secret-volume-pod
spec:
  containers:
    - name: test-container
      image: alpine
      command: ["sleep", "3600"]
      volumeMounts:
      - name: keys-volume
        mountPath: "/etc/secure-keys"
        readOnly: true 
  volumes:
    - name: keys-volume
      secret:
        secretName: api-keys