apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ai-backend-credentials
  namespace: default
spec:
  refreshInterval: "15s" 
  secretStoreRef:
    name: simulated-enterprise-vault
    kind: SecretStore
  target:
    name: ai-vault-secret
    creationPolicy: Owner
  data:
    - secretKey: db-password
      remoteRef:
        key: production/database/password
    - secretKey: api-key
      remoteRef:
        key: production/api/openai-key