apiVersion: v1
kind: Pod
metadata:
  name: sidecar-log-shipper
spec:
  volumes:
  - name: shared-logs
    emptyDir: {} 
  containers:
  - name: primary-app
    image: alpine
    command: ['sh', '-c', 'while true; do echo "$(date) - ERROR: Payment Gateway Timeout" >> /var/log/shared/errors.log; sleep 5; done']
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log/shared
  - name: log-forwarder-agent
    image: busybox:1.28
    command: ['sh', '-c', 'tail -f /var/log/shared/errors.log']
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log/shared