apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: transaction-ledger
  namespace: kafka
  labels:
    strimzi.io/cluster: enterprise-broker
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824