apiVersion: apps/v1
kind: Deployment
metadata:
  name: enterprise-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: enterprise-api
  template:
    metadata:
      labels:
        app: enterprise-api
    spec:
      containers:
      - name: api
        image: darkangel689/enterprise-api:6e281ee1c1505dc63a287f4e377166f39cec8beb
        ports:
        - containerPort: 3000