apiVersion: v1
kind: Namespace
metadata:
  name: legacy-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unencrypted-rogue-client
  namespace: legacy-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rogue-client
  template:
    metadata:
      labels:
        app: rogue-client
    spec:
      containers:
      - name: client
        image: curlimages/curl:latest
        command: ["/bin/sh", "-c", "sleep 3600"]