---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-db-password
  namespace: default
spec:
  encryptedData:
    password: AgCQUli9WNmp0AgP9TeoHp0oLpkSSadgNIATmI/b6Tl4DqnZKw7luU4W1mICbsHc3qXRQNKUSGllY+IRtSrRZBsvStO9XzX6FuE1ZrA43KS66NQAXXCXe3Mb0Fj2khhGjcBvEArSagNA6i6qbzUD4/uQUNe5/mk7mKJoGh9vAJHf7B3rzUWRx//2f5bHdVz6GhHJjHIq0FYrD/0tg16sNF3/JpzGIxliFF2LK7hlYG+i4kBisKmtyn6VOL/sxe+Dz6n4nTfyrWDXUFIfegdM4XNaNyaG+A0OwJ9UNhYw9Tr1lrJgFEPtXvJBafBaUkKCCVJCs1EK8TMIjOJJBDReNrs5pXQKskvEzGVCZujoNa3MOgVnHtSSbeO4bHigafZ1RCtJNoB1P2Ti2m2d45gPYQEVTgpwW9oRLOItc2XinbPzVVxIY+u5z1c68wU99AhCcssDKF7GjBITursnguX2lxRcF5u2giLIL/fBdnqwrQyYU8x8dVIAnzEuzWmRUHBFNr0MiXEjLGJLSzWt6pdNBmDkIUHvpVCQ6vchTfsea/eJLCbajOixMCefc42FQKe34nDNSkGNRPJu6Z3PJSwtxvSDXRvFu3XeGAPr0EYGM2iisw6KPNlIIPMYwEW4ypP5ix87SVrrTKptJ+wNKuHiIe7dXGVr26+qNdFLh/a5dasCcxO9ySHIzLA312CYZQAHnG+GOqKz1fPXzpNrjhXu0aiBb860HE0=
  template:
    metadata:
      creationTimestamp: null
      name: my-db-password
      namespace: default
