---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-db-password
  namespace: default
spec:
  encryptedData:
    password: AgAytPwBqDh48ClaiRnF9NSO7KLsYNPrUX4cdBCo4HtmqzR1MuV+m9GY4f/wRAltt0hq657BYs4QNTx0e3OSIKb0pBTnXTRR/YOiEg+ZLt4IMA6y/vKxDTM1t881rC+KRd7NVHCvp+yEqdMXmsy392mslrKGNS1rUvH9ouPRP/4ICRaRsL0lo3Lhjo92zs/FSB8fnJWC5AA5O4guihy7mB1RoigK3JSO5PDifpocVxL9FqkMQ5Cy/00WfGMgmRV9u7IbfHFxE8I2hymIDMW5X7T6eN9XN1m70dS7PvJ/GUHuiIW9oXVEEyxE/6kUGHj0HPizJTD3kr+DZW/bdPHcNi5UygjhftzRvLXVIWdPJZOszzcSDN8TekughJcFRiaDi/4yABsjwj+RK5oSD24ngmF2CwgqYn+dYdMwlS2qT68VghUWTHHBz1wu49IBUMXm7eBp9fsw4uRtTBXGc7yycPRn4x4rYS1/TXUawOs9+PO6YTO/gIB4sVG88e2ic1hJzEhqz5ILq+pnOCrZ8dTfGaTA+ICONdG8cKI0IHWyMOenxT0Sq50wxMESyK0GFnTbtzoBHUYwq7BoeBr1sj9aTN7+DUsM93JIkiKJ3sG3x5LuLVEN0DGXEdOCouhiu8dIaaijlJ/jDmXC49+yolB/h2qvmr9sj152BXPD+guWdE6DB01kE6G6LF2pOiYoNIEWplBf8uDUOtOLpWDxLDnE5as59Pv628Bx1Ak4QQ==
  template:
    metadata:
      creationTimestamp: null
      name: my-db-password
      namespace: default
