apiVersion: v1
kind: Pod
metadata:
  name: env-app
spec:
  containers:
  - name: my-app
    image: alpine
    command: ["sleep", "3600"]
    envFrom:
    - configMapRef:
        name: frontend-settings 