apiVersion: v1
kind: Pod
metadata:
  name: file-app
spec:
  containers:
  - name: my-app
    image: alpine
    command: ["sleep", "3600"]
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config 
  volumes:
  - name: config-volume
    configMap:
      name: frontend-settings