apiVersion: v1
kind: Pod
metadata:
  name: guaranteed-pod
spec:
  containers:
  - name: vip-app
    image: alpine
    command: ["sleep", "3600"]
    resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "100Mi" 