apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: advanced-gitops-pipeline
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/DARKANGEL689/100-Days-Of-Docker.git'
    path: Day-17-GitOps/advanced-infrastructure 
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas 