apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-api-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: disk-tier
                operator: In
                values:
                - nvme
      containers:
      - name: api
        image: alpine
        command: ["sleep", "3600"]
