---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-database-password
  namespace: default
spec:
  encryptedData:
    db-password: AgCVh+LAG/iwH1KhKY+uIktywp3nuyjU/phZJLRItP70XQcgPc07kzTmt6bLaeXP2Ethif5M4gh8EsHdQaeP3V9dfP++eu2ZNKByXHkN8IwTChMj1sXRUo7yPMMMJKT19qdeyxXt57rcShH1nETTB2VKmjlrgPKMTQHi2naXzU2xMyDuZ4Sjc9f+hw6ofjWvhzfibywp0hlEEfQpnfaiKBkXJcZYTQ2Ui3+MxBPI3GukNbFwQJMnll15kxNNY90u8ttdkSjmo59WZiXFKlEQzkAVoPG5rCw/+x8NPPcbyOUOmyMnJXLterHHhtogagw37ZPXpCEu0gQBYS5AV4/wKxt8RrXZ/6SEqpTK1ZeSCWT4b3xV8UWsGbIPNftQhQ/Wsh0m2uYgmKlQOnauRF2wgnSoQBisodBWdHOVY4RHuQERgzg9CmfXcvj5IwTD6xebqcTWeLUbFE8YsFpUzrOhVZDZeCGAgGzk8mjbPG66w4OD9I8rstWgQoIKJzVO8QDJ1MHaop6WSQvMJjZrcngl1QdWWXQ+R2Q6w3kAPND3SoWA5YJu0vO6ifqt4AO13Un/d4Kcgra6NAwIUcbOrWa8QqnaC/Qcb3E6QEwTJiOKTN41pzoDbTMB1ZnkBBFE+HPoXU0qyCoLOvMjgkW0bAQCBnPnc5Jvs0Tz9exSBq3Sr+uunuK/ofWIZO4Cr9vE9flnJvJEbjwXpSUnWP0erZ5TfgSKxVt38Wtwah34XRfHmDA1VA==
  template:
    metadata:
      creationTimestamp: null
      name: my-database-password
      namespace: default
    type: Opaque
