apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-webapp
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gitops-web
  template:
    metadata:
      labels:
        app: gitops-web
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80