apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-feature-store
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-store
  template:
    metadata:
      labels:
        app: redis-store
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-feature-svc
  namespace: default
spec:
  selector:
    app: redis-store
  ports:
    - port: 6379
      targetPort: 6379